spring:
  application:
    name:
      StoreManagement
  server:
    port:
      8080
  datasource:
    url:
      jdbc:postgresql://localhost:5432/YOUR_DATABASE
    username:
      YOUR_USERNAME
    password:
      YOUR_PASSWORD
  jpa:
    hibernate:
      ddl-auto:
        update
    database-platform:
      org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql:
      true
    open-in-view: false